# Generated by Django 5.1.4 on 2025-01-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('category', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages'), ('Soups', 'Soups'), ('Vegan', 'Vegan'), ('Non-Veg', 'Non-Veg'), ('Pure Veg', 'Pure Veg'), ("Chef's Special", "Chef's Special"), ('Jain', 'Jain')], max_length=50)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_jain_option', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_non_veg', models.BooleanField(default=False)),
                ('is_pure_veg', models.BooleanField(default=False)),
                ('is_chefs_special', models.BooleanField(default=False)),
                ('is_soup', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='accounts.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=25)),
                ('seats', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.restaurant')),
            ],
        ),
    ]
