# Generated by Django 5.1.4 on 2025-01-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type_customer'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='unique_table_number_per_restaurant'),
        ),
    ]
