# Generated by Django 5.1.4 on 2025-01-05 08:45

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='table_qr/'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_code',
            field=models.CharField(default=restaurant.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
