# Generated by Django 5.1.4 on 2025-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_qr_code_image_table_table_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='bill_paid',
            field=models.BooleanField(default=False),
        ),
    ]
