# Generated by Django 5.1.4 on 2025-01-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_table_bill_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='table',
            name='unique_table_number_per_restaurant',
        ),
    ]
