# Generated by Django 5.1.4 on 2025-01-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_table_unique_table_number_per_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='bill_paid',
            new_name='BILL_PAID',
        ),
    ]
