# Generated by Django 5.1.4 on 2025-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='emp_login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('customer', 'Customer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
