# Generated by Django 5.1.4 on 2025-01-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cartitem_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='restaurant',
            new_name='qr_code',
        ),
    ]
