# Generated by Django 5.1.4 on 2025-01-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_is_active'),
        ('customer', '0004_rename_qr_code_cartitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='table_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
