# Generated by Django 5.1.4 on 2025-01-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_order_status'),
        ('restaurant', '0004_table_qr_code_image_table_table_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
        ),
    ]
