# Generated by Django 5.1.4 on 2025-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Cooking', 'Cooking'), ('Ready_to_serve', 'Ready to Serve'), ('Bill_Paid', 'Bill_Paid')], default='Pending', max_length=50),
        ),
    ]
