# Generated by Django 5.2.17 on 2026-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cooking', 'Cooking'), ('Ready_to_serve', 'Ready_to_serve'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Bill_Paid', 'Bill_Paid')], default='Pending', max_length=50),
        ),
    ]
