sonar.projectKey=serveware
sonar.projectName=ServeWare
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests.py
sonar.exclusions=**/migrations/**,**/static/**,**/staticfiles/**,**/media/**,**/templates/**,htmlcov/**,test-reports/**,**/tests.py,testutils.py
sonar.coverage.exclusions=manage.py,serveware/asgi.py,serveware/wsgi.py,**/management/**
sonar.cpd.exclusions=**/migrations/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
# sonar.python.xunit.reportPath=test-reports/*.xml
sonar.sourceEncoding=UTF-8
